//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTestV1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFLandenStedenTalenEntities : DbContext
    {
        public EFLandenStedenTalenEntities()
            : base("name=EFLandenStedenTalenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Landen> Landen { get; set; }
        public virtual DbSet<Steden> Steden { get; set; }
        public virtual DbSet<Talen> Talen { get; set; }
    }
}
